version: '3.7'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev # The name of the docker config file
      context: ./nginx
    # volumes:
    # - ./nginx:/etc/nginx/conf.d/
    ports:
      - '3051:80'
  client:
    container_name: client
    restart: always
    build:
      dockerfile: Dockerfile.dev # The name of the docker config file
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  auth-service:
    container_name: auth-service
    restart: always
    build:
      dockerfile: Dockerfile.dev # The name of the docker config file
      context: ./auth-service
    volumes:
      # - /app/node_modules
      - ./auth-service:/app
    # ports:
    #   - '30502:3000'
    links:
      - mongo
    environment:
      - REDIS_DB_URI=redis
      - REDIS_DB_PORT=6379
      - MONGO_DB_URI=mongodb://mongo:27017/auth-service-db
      - JWT_KEY=nh7dd4456vhbgkjvdDWQZXMKOY6FDEAmkbZMOPI
      # - db_retry_time=3000
  # user-service:
  # product-service:
  # cart-service:
  # order-service:
  # payment-service:
  mongo:
    container_name: mongo-db
    image: mongo
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - '27017:27017'
  redis:
    container_name: redis-db
    image: redis
    restart: always
  # rabbitmq:
  # worker:
